// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViventiumTest.Models;

#nullable disable

namespace ViventiumTest.Migrations
{
    [DbContext(typeof(ViventiumTestDbContext))]
    partial class ViventiumTestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("ViventiumTest.Models.Company", b =>
                {
                    b.Property<uint>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ViventiumTest.Models.Employee", b =>
                {
                    b.Property<uint>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeDepartment")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeFirstName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmployeeHireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeLastName")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ViventiumTest.Models.Employee", b =>
                {
                    b.HasOne("ViventiumTest.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ViventiumTest.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
